# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.



title: 道源
titleline: 每一份执着,都来源于你的坚持
tagline: 执着于每一行代码,也是另外一种享受生活方式
baseurl:
url:
assets: /assets
port: 80

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

highlighter: rouge

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM


widgets:
  - category
  - tag
#  - links
  - wechatCgi
  - github

language: zh-CN

menu:
  源码学习: /archives
  历史文章: /
  关于: /about

paginate: 10

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

author:
  name: 道源
  github: https://github.com/raoshihong

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.

index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: 阅读更多

#### Analytics
google_analytics:
  enable: false
  id:
  site:
baidu_analytics:
  enable: true
  sitecode: 6412f0c01e8c372d398d3bd9f737bf06

totop: true

mathjax: true